apiVersion: apps/v1 # 接口版本
kind: Deployment    # 接口类型
metadata:
  name: rush-rpc    # deployment name
  labels:
    app: rush-rpc
spec:
  replicas: 1       # pod数
  selector:
    matchLabels:    
      app: rush-rpc 
  template:
    metadata:
      labels:
        app: rush-rpc # 模板名称
    spec:             # 定义容器模板 
      containers:     # -command -arg可选 不填默认配置
        - name: rush-rpc
          image: hkccr.ccs.tencentyun.com/rush-rpc
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred