apiVersion: v1
kind: Service
metadata:
  name: rush-rpc-service
  namespace: default
  labels:
    app: rush-rpc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
  selector:
    app: rush-rpc